main: com.alchemi.tc.Main
version: 1.0
name: TranslationCircuit

commands:
    tc send:
        description: Send a private message
        usage: /tc send [player] [message]
    
    tc mute:
        description: Mute a bad player
        usage: /tc mute [player]
    
    tc unmute:
        description: Unmute a player
        usage: /tc mute [player]
        
    tc group:
        description: Group chat manager
        usage: /tc group help
        
    tc reply:
        description: Reply to your last private message
        usage: /reply [message]
        aliases: [r]
        
permissions:
    tc:
        privatechat:
            default: player
        
        mute:
            default: op
            
        unmute:
            default: op
            
        colorchat:
            default: player